a_pjt_login/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("detail/<int:pk>/update/", views.update, name="update"),
    path('detail/<int:pk>/delete/', views.delete, name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

reviews/models.py
from email.policy import default
from turtle import title
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    movie_name = models.CharField(max_length=20)
    grade = models.FloatField(
        default=1, validators=[MaxValueValidator(5), MinValueValidator(0)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            "username",
            "email",
        )

reviews/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["title", "content", "movie_name", "grade"]
        labels = {
            "title": "리뷰 제목",
            "content": "리뷰 내용",
            "movie_name": "영화 제목",
            "grade": "평점(0~5)",
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    users = get_user_model().objects.all()
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)


def signup(request):

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("accounts:index")
    else:
        form = CustomUserCreationForm()

    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.user.is_authenticated:
        return redirect("accounts:index")
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "accounts:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:login")


@login_required
def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            # 비밀번호 변경시 index 페이지로
            update_session_auth_hash(request, form.user)
            return redirect("accounts:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)

reviews/views.py
from django.shortcuts import render, redirect

import reviews
from .forms import ReviewForm
from .models import Review
from reviews import forms

# Create your views here.
def index(request):

    reviews = Review.objects.order_by("-created_at")
    context = {
        "reviews": reviews,
    }

    return render(request, "reviews/index.html", context)


def create(request):
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect("reviews:index")
    else:
        review_form = ReviewForm()

    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/create.html", context)


def detail(request, pk):
    review = Review.objects.get(pk=pk)

    context = {
        "review": review,
    }
    return render(request, "reviews/detail.html", context)


def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect("reviews:index")
    else:
        review_form = ReviewForm(instance=review)
    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/update.html", context)


def delete(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        review.delete()
        return redirect("reviews:index")
    else:
        return redirect("reviews:detail", review.pk)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<h1>비밀번호 수정</h1>
<form action="" method="POST">
  {% csrf_token %} {% bootstrap_form form %}
  <button type="submit" class="btn btn-outline-dark">수정</button>
  <button
    type="button"
    class="btn btn-outline-dark"
    onclick="location.href='{% url 'accounts:index' %}' "
  >
    돌아가기
  </button>
</form>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<h1>상세 회원 정보</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">user</th>
      <th scope="col">email</th>
      <th scope="col">last_login</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{ user.username}}</th>
      <td>{{ user.email}}</td>
      <td>{{ user.last_login}}</td>
    </tr>
  </tbody>
</table>
<button type="button" class="btn btn-outline-dark" onclick="location.href='{% url 'accounts:index' %}' ">돌아가기</button>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<h1>회원 목록</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">user</th>
      <th scope="col">email</th>
      <th scope="col">last_login</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
    <tr>
      <th scope="row">{{ user.username}}</th>
      <td>{{ user.email}}</td>
      <td>{{ user.last_login}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>login</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-dark" onclick="location.href='{% url 'accounts:index' %}' ">로그인</button>

  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<h1>signUp</h1>
<form action="" method="POST">
  {% csrf_token %} {% bootstrap_form form %}
  <button type="submit" class="btn btn-outline-dark" >제출</button>

</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<h1>update</h1>
<form action="" method="POST">
  {% csrf_token %} {% bootstrap_form form %}
  <input type="submit" value="제출" />
  <button type="button" class="btn btn-outline-dark" onclick="location.href='{% url 'accounts:index' %}' ">돌아가기</button>
</form>
{% endblock content %}

config/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Document</title>
    {% bootstrap_css %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'accounts:index' %}">Movie</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:update' %}">회원 정보 수정</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:change_password' %}">비밀 번호 수정</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-5">

      {% block content %}{% endblock content %}
    </div>
    <!-- JavaScript Bundle with Popper -->
    {% bootstrap_javascript %}
  </body>

</html>

reviews/templates/reviews/create.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<h1>Create</h1>
<form action="" method="POST">
  {% csrf_token %} {% bootstrap_form review_form %}
  <button type="submit" class="btn btn-outline-dark">생성</button>
</form>
{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<h2 class="text-center fw-bold">{{review.title}}</h2>
<hr />
<h3 class="d-flex justify-content-between">
  {{review.movie_name}}<span><small>⭐{{review.grade}}</small></span>
</h3>

<hr />
<p>{{review.content}}</p>

<div class="d-flex">
  <button
    type="submit"
    class="btn btn-outline-dark"
    onclick="location.href='{% url 'reviews:update' review.pk %}' "
  >
    수정
  </button>
  <form
    class="mx-2"
    action="{% url 'reviews:delete' review.pk %}"
    method="POST"
  >
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-danger">삭제</button>
  </form>
</div>
{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<h1 class="text-center fw-bold">리뷰 목록</h1>
<div class="d-flex justify-content-end">
  <button
    type="submit"
    class="btn btn-outline-dark my-3"
    onclick="location.href='{% url 'reviews:create' %}' "
  >
    작성하기
  </button>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">리뷰 제목</th>
      <th scope="col">영화 이름</th>
      <th scope="col">평점</th>
    </tr>
  </thead>
  <tbody>
    {% for review in reviews %}
    <tr>
      <th scope="row">
        <a
          href="{% url 'reviews:detail' review.pk %}"
          style="text-decoration: none"
          >{{ review.title}}</a
        >
      </th>
      <td>{{ review.movie_name}}</td>
      <td>{{ review.grade }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<h1>Update</h1>
<form action="" method="POST">
  {% csrf_token %} {% bootstrap_form review_form %}
  <button type="submit" class="btn btn-outline-dark">수정</button>
</form>
{% endblock content %}